# Generated by Django 5.0.1 on 2024-01-21 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regform',
            name='nameofcollege_organization',
        ),
        migrations.RemoveField(
            model_name='regform',
            name='yearofgraduation',
        ),
    ]
