# Generated by Django 5.0.1 on 2024-01-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_regform_nameofcollege_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regform',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('transgender', 'Transgender'), ('notSpecified', 'NotSpecified')], default='notSpecified', max_length=20),
        ),
    ]
