# Generated by Django 5.0.1 on 2024-01-22 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contacthome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacthome',
            options={'verbose_name': 'ContactHome', 'verbose_name_plural': 'ContactHome'},
        ),
    ]
