# Generated by Django 5.0.1 on 2024-01-22 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_contacthome_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacthome',
            options={'verbose_name': 'Contact Form', 'verbose_name_plural': 'Contact Forms'},
        ),
    ]
