# Generated by Django 5.0.1 on 2024-01-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contactform_delete_contacthome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='homeContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=125)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
